export const SUBJECTS = {
  sem1: [
    { name: 'Engineering Chemistry', key: 'chemistry' },
    { name: 'Engineering Maths 1', key: 'maths1' },
    { name: 'Engineering Physics', key: 'physics' },
    { name: 'Engineering Maths 2', key: 'maths2' },
    { name: 'Soft Skill', key: 'softskill' },
    { name: 'Environment and Ecology', key: 'environment' },
    { name: 'Programming for Problem Solving', key: 'pps' },
    { name: 'Fundamentals of Electrical Engg', key: 'electrical' },
    { name: 'Fundamentals of Mechanical Engg', key: 'mechanical' },
    { name: 'Fundamentals of Electronics Engg', key: 'electronics' },
  ],

  sem2: [
    { name: 'Engineering Chemistry', key: 'chemistry' },
    { name: 'Engineering Maths 1', key: 'maths1' },
    { name: 'Engineering Physics', key: 'physics' },
    { name: 'Engineering Maths 2', key: 'maths2' },
    { name: 'Soft Skill', key: 'softskill' },
    { name: 'Environment and Ecology', key: 'environment' },
    { name: 'Programming for Problem Solving', key: 'pps' },
    { name: 'Fundamentals of Electrical Engg', key: 'electrical' },
    { name: 'Fundamentals of Mechanical Engg', key: 'mechanical' },
    { name: 'Fundamentals of Electronics Engg', key: 'electronics' },
  ],

  sem3: [
    { name: 'Data Structures', key: 'dsa' },
    { name: 'Digital Electronics', key: 'digital' },
    { name: 'DSTL', key: 'dstl' },
    { name: 'Cyber Security', key: 'cyber' },
    { name: 'Python Programming', key: 'python' },
    { name: 'UHV', key: 'uhv' },
    { name: 'Technical Communication', key: 'tc' },
    { name: 'COA', key: 'coa' },
    { name: 'Maths 4', key: 'maths4' },
  ],

  sem4: [
    { name: 'Operating System', key: 'os' },
    { name: 'Maths 4', key: 'maths4' },
    { name: 'Digital Electronics', key: 'digital' },
    { name: 'Object Oriented Programming with Java', key: 'oop_java' },
    { name: 'Technical Communication', key: 'tc' },
    { name: 'COA', key: 'coa' },
    { name: 'Microprocessor', key: 'micro' },
    { name: 'UHV', key: 'uhv' },
    { name: 'Theory of Automata and Formal Languages', key: 'tafl' },
    { name: 'Cyber Security', key: 'cyber' },
    { name: 'Python Programming', key: 'python' },
  ],

  sem5: [
    { name: 'Database Management System', key: 'dbms' },
    { name: 'Design and Analysis of Algorithm', key: 'daa' },
    { name: 'Web Technology', key: 'wt' },
    { name: 'Constitution of India', key: 'coi' },
    { name: 'Essence of Indian Traditional Knowledge', key: 'eitk' },
    { name: 'Data Analytics', key: 'da' },
    { name: 'Computer Graphics', key: 'cg' },
    { name: 'Object Oriented System Design with C++', key: 'oosd_cpp' },
    { name: 'Machine Learning Techniques', key: 'ml' },
    { name: 'Application of Soft Computing', key: 'sc' },
    { name: 'Image Processing', key: 'ip' },
    { name: 'Data Warehousing & Data Mining', key: 'dwdm' },
  ],

  sem6: [
    { name: 'Software Engineering', key: 'se' },
    { name: 'Compiler Design', key: 'cd' },
    { name: 'Computer Networks', key: 'cn' },
    { name: 'Constitution of India', key: 'coi' },
    { name: 'Essence of Indian Traditional Knowledge', key: 'eitk' },
    { name: 'Big Data', key: 'bd' },
    { name: 'Augmented & Virtual Reality', key: 'arvr' },
    { name: 'Blockchain Architecture Design', key: 'bad' },
    { name: 'Data Compression', key: 'dc' },
    { name: 'Data Analytics', key: 'analytics' },
    { name: 'Computer Graphics', key: 'computer_graphics' },
    { name: 'Object Oriented System Design with C++', key: 'oosd_cpp' },
  ],

  sem7: [
    { name: 'Artificial Intelligence', key: 'ai' },
    { name: 'Deep Learning', key: 'dl' },
    { name: 'Internet of Things', key: 'iot' },
    { name: 'Vision of Human Society', key: 'vhs' },
    { name: 'Renewable Energy Resources', key: 'rer' },
    { name: 'Project Management', key: 'pme' },
    { name: 'Intro To Women & Gender Studies', key: 'itgs' },
    { name: 'Cryptography and Network Security', key: 'crypto' },
    { name: 'Data Warehousing and Data Mining', key: 'dwdm' },
    { name: 'Cloud Computing', key: 'cloud' },
    { name: 'Rural Development Administration & Planning', key: 'rdap' },
    { name: 'Design Development of Application', key: 'dda' },
    { name: 'Natural Language Processing', key: 'nlp' },
  ],

  sem8: [
    { name: 'Artificial Intelligence', key: 'ai' },
    { name: 'Deep Learning', key: 'dl' },
    { name: 'Internet of Things', key: 'iot' },
    { name: 'Vision of Human Society', key: 'vhs' },
    { name: 'Renewable Energy Resources', key: 'rer' },
    { name: 'Project Management', key: 'pme' },
    { name: 'Intro To Women & Gender Studies', key: 'itgs' },
    { name: 'Cryptography and Network Security', key: 'crypto' },
    { name: 'Data Warehousing and Data Mining', key: 'dwdm' },
    { name: 'Cloud Computing', key: 'cloud' },
    { name: 'Rural Development Administration & Planning', key: 'rdap' },
    { name: 'Design Development of Application', key: 'dda' },
    { name: 'Natural Language Processing', key: 'nlp' },
  ],
};
export default SUBJECTS; // 👈 MUST